<?php

defined('GLOBAL_ERROR_MSG') OR define('GLOBAL_ERROR_MSG', "Ooos! some error occured, please try again");

defined('GOOGLE_MAP_API_KEY') OR define('GOOGLE_MAP_API_KEY', "AIzaSyDpavHXELJMJvIHifFPN6tBBiFSXKGpy2g");


defined('STRIPE_PUBLISHABLE_KEY_TEST') OR define('STRIPE_PUBLISHABLE_KEY_TEST', "pk_test_51Gs9gYLmUP6RqXa43t1ZDP5IHvxCaKLtDc4BsdAzW2a9Oy913JknTJVPQH76BXgdGUg3CDpN6eFWrxoK8rJebe2Q00RZiv0XW0");
defined('STRIPE_SECRET_KEY_TEST') OR define('STRIPE_SECRET_KEY_TEST', "sk_test_51Gs9gYLmUP6RqXa4EaxSbolfZTGA3PSDKEtwESFw3stFSYlO1G1LollUNdT7FPxOyQkeEBYc9IaaEuzR7Go5WAwk00ZMaoTuRh");
?>
